title: Self Learning Certification in Data Science
description: >-
  This course is designed for everyone to learn from anywhere, irrespective of
  their educational background. It has been tailor made as per the learner's
  need and updated with the current market standards for those who want to have
  a career in Data Science!
template:
  repo: self-learning-certification-in-data-science-template
  name: Data Science Novice
  description: >-
    In this course, learner's will get to know the basics of Data Science, as in
    where to start and what all things are requiered to focus on in order to be
    mark their footsteps in the futuristic industry.
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Induction
    description: >-
      This marks the beginning of the our journey, where we will learn together
      the fundamentals of Data Science, understanding how data is imapcting our
      day to day lives.
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
    video: 'https://youtu.be/embed/eJR-oTEEDhU'
